title: 2024 Capstone Design
description: A starter template for a Jekyll site using the Just the Docs theme!
theme: just-the-docs

url: https://em0yes.github.io

aux_links:
  Template Repository: https://github.com/em0yes/em0yes.github.io

# Navigation
nav:
  - title: "Home"
    url: "/"
  - title: "주간 회의록"
    url: "/pages/weekly-meeting/"
  - title: "주간 보고서"
    url: "/pages/weekly-reports/"
  - title: "Contribution Log"
    url: "/pages/contribution-log/"
    children:
      - title: "김지윤"
        url: "/contribution-log/kim-ji-yoon/"
      - title: "박수진"
        url: "/pages/contribution-log/park-su-jin/"
      - title: "정지원"
        url: "/pages/contribution-log/jung-ji-won/"
      - title: "이다은"
        url: "/pages/contribution-log/lee-da-eun/"

