title: 2024 Capstone Design
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://em0yes.github.io

aux_links:
  Template Repository: https://github.com/em0yes/em0yes.github.io
