title: 2024 Capstone Design
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://em0yes.github.io

aux_links:
  Template Repository: https://github.com/em0yes/em0yes.github.io

# Navigation
nav:
  - title: "Home"
    url: "/"
  - title: "Weekly Meeting Minutes"
    url: "/weekly-meeting-minutes/"
  - title: "Weekly Reports"
    url: "/weekly-reports/"
  - title: "Contribution Log"
    items:
      - title: "Kim Ji-yoon"
        url: "/contribution-log/Kim Ji-yoon/"
      - title: "Park Su-jin"
        url: "/contribution-log/Park Su-jin/"
      - title: "Jung Ji-won"
        url: "/contribution-log/Jung Ji-won/"
      - title: "Lee Da-eun"
        url: "/contribution-log/Lee Da-eun/"
